"""split_plugins_i18n

Revision ID: a564f55fdea8
Revises: 
Create Date: 2026-02-04 10:50:19.211036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a564f55fdea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_category_tenant_slug')
    )
    op.create_index(op.f('ix_category_tenant_id'), 'category', ['tenant_id'], unique=False)
    op.create_index('ix_category_tenant_parent', 'category', ['tenant_id', 'parent_id'], unique=False)
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_key'), 'plugins', ['key'], unique=True)
    op.create_table('category_translation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category_id', 'locale', name='uq_category_tr')
    )
    op.create_index('ix_category_tr_tenant_locale', 'category_translation', ['tenant_id', 'locale'], unique=False)
    op.create_index(op.f('ix_category_translation_tenant_id'), 'category_translation', ['tenant_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_product_tenant_slug')
    )
    op.create_index('ix_product_tenant_category', 'product', ['tenant_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_table('tenant_plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'plugin_id')
    )
    op.create_index(op.f('ix_tenant_plugins_tenant_id'), 'tenant_plugins', ['tenant_id'], unique=False)
    op.create_table('product_alias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('alias_norm', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'locale', 'alias_norm', name='uq_product_alias_norm')
    )
    op.create_index(op.f('ix_product_alias_tenant_id'), 'product_alias', ['tenant_id'], unique=False)
    op.create_index('ix_product_alias_tenant_locale', 'product_alias', ['tenant_id', 'locale'], unique=False)
    op.create_table('product_translation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'locale', name='uq_product_tr')
    )
    op.create_index('ix_product_tr_tenant_locale', 'product_translation', ['tenant_id', 'locale'], unique=False)
    op.create_index(op.f('ix_product_translation_tenant_id'), 'product_translation', ['tenant_id'], unique=False)
    op.create_table('product_variant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('variant_key', sa.String(length=50), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'product_id', 'variant_key', name='uq_product_variant_key')
    )
    op.create_index(op.f('ix_product_variant_tenant_id'), 'product_variant', ['tenant_id'], unique=False)
    op.create_index('ix_product_variant_tenant_product', 'product_variant', ['tenant_id', 'product_id'], unique=False)
    op.create_table('product_variant_translation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'variant_id', 'locale', name='uq_product_variant_tr')
    )
    op.create_index(op.f('ix_product_variant_translation_tenant_id'), 'product_variant_translation', ['tenant_id'], unique=False)
    op.create_index('ix_variant_tr_tenant_locale', 'product_variant_translation', ['tenant_id', 'locale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_variant_tr_tenant_locale', table_name='product_variant_translation')
    op.drop_index(op.f('ix_product_variant_translation_tenant_id'), table_name='product_variant_translation')
    op.drop_table('product_variant_translation')
    op.drop_index('ix_product_variant_tenant_product', table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_tenant_id'), table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_index(op.f('ix_product_translation_tenant_id'), table_name='product_translation')
    op.drop_index('ix_product_tr_tenant_locale', table_name='product_translation')
    op.drop_table('product_translation')
    op.drop_index('ix_product_alias_tenant_locale', table_name='product_alias')
    op.drop_index(op.f('ix_product_alias_tenant_id'), table_name='product_alias')
    op.drop_table('product_alias')
    op.drop_index(op.f('ix_tenant_plugins_tenant_id'), table_name='tenant_plugins')
    op.drop_table('tenant_plugins')
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index('ix_product_tenant_category', table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_category_translation_tenant_id'), table_name='category_translation')
    op.drop_index('ix_category_tr_tenant_locale', table_name='category_translation')
    op.drop_table('category_translation')
    op.drop_index(op.f('ix_plugins_key'), table_name='plugins')
    op.drop_table('plugins')
    op.drop_index('ix_category_tenant_parent', table_name='category')
    op.drop_index(op.f('ix_category_tenant_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
