/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+08ace69c460bdfc4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+08ace69c460bdfc4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+08ace69c460bdfc4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+df0ebcb75a26201e/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+08ace69c460bdfc4/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.bun/@nuxt+ui@3.3.7+08ace69c460bdfc4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  }
}
